spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.100:3306/super_work?useTimezone=true&serverTimezone=Asia/Shanghai&useunicode=true&characterEncoding=utf8
    username: username
    password: password
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 ,log4j被删除
    filters: stat,wall,log4j2
    filter:
      commons-log:
        #data-source-log-enabled: true
        statement-log-enabled: false
        statement-executable-sql-log-enable: false
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  rabbitmq:
    host: 192.168.50.100
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        retry:
          # 开启重试
          enabled: true
          # 重试三次
          max-attempts: 3
          # 间隔时间1s
          max-interval: 1000
  redis:
    #Linux主机地址
    host: 192.168.50.100
    #端口
    port: 6379
    #密码
    password: .password
    timeout: 3000000
    jedis:
      pool:
        #最大连接数目
        max-active: 10
        #连接最大等待时间
        max-wait: 30000ms
        #连接最大等待时间
        max-idle: 10
    database: 2
path:
  image: "temp/image/"
