server:
  tomcat:
    uri-encoding: utf-8
  port: 2191 #2189
spring:
  application:
    name: super_work-server
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  # 开启循环引用
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      # 路径匹配规则
      matching-strategy: ANT_PATH_MATCHER
logging:
  level:
    root: info
    javax.activation: info
    org.apache.catalina: info
    org.apache.commons.beanutils.converters: info
    org.apache.coyote.http11.Http11Processor: info
    org.apache.http: info
    org.apache.tomcat: info
    org.springframework: info
    com.chinamobile.cmss.bdpaas.resource.monitor: debug
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.saki.work.moudel.po.*,com.saki.work.system.moudel.po.*
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_ID
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    # 是否输出debug
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分布式文件系统fastdfs配置
swagger:
  production: false
  basic:
    enable: true
    username: username
    password: password
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 2592000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
